platform :ios, '11.0'

target 'JitsiSDKTest' do
    pod 'JitsiMeetSDK', '~> 3.0.2'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
end
