platform :ios, '14.0'

target 'Broadcast Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Broadcast Extension

end

target 'JitsiSDKScreenSharingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JitsiSDKScreenSharingTest
  pod 'JitsiMeetSDK', '9.2.1'

end
