# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Broadcast Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Broadcast Extension

end

target 'JitsiSDKScreenSharingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JitsiSDKScreenSharingTest
  pod 'JitsiMeetSDK', '3.6.0'

end
